/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ConstructorRouteImport } from './routes/constructor'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as WorksRouteImport } from './routes/works'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogSlugRouteImport } from './routes/catalog.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorRoute = ConstructorRouteImport.update({
  id: '/constructor',
  path: '/constructor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/constructor': typeof ConstructorRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/works': typeof WorksRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/constructor': typeof ConstructorRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/works': typeof WorksRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/catalog': typeof CatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/constructor': typeof ConstructorRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/reviews': typeof ReviewsRoute
  '/works': typeof WorksRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/constructor'
    | '/contacts'
    | '/delivery'
    | '/faq'
    | '/reviews'
    | '/works'
    | '/catalog/$slug'
    | '/legal/$slug'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/constructor'
    | '/contacts'
    | '/delivery'
    | '/faq'
    | '/reviews'
    | '/works'
    | '/catalog/$slug'
    | '/legal/$slug'
    | '/catalog'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/constructor'
    | '/contacts'
    | '/delivery'
    | '/faq'
    | '/reviews'
    | '/works'
    | '/catalog/$slug'
    | '/legal/$slug'
    | '/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ConstructorRoute: typeof ConstructorRoute
  ContactsRoute: typeof ContactsRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  ReviewsRoute: typeof ReviewsRoute
  WorksRoute: typeof WorksRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructor': {
      id: '/constructor'
      path: '/constructor'
      fullPath: '/constructor'
      preLoaderRoute: typeof ConstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ConstructorRoute: ConstructorRoute,
  ContactsRoute: ContactsRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  ReviewsRoute: ReviewsRoute,
  WorksRoute: WorksRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
